// Central Registry for Developer Tools & API Explorer
// Only registered RGEnterprises API routes are permitted to be probed.

import { ApiExplorerRoute } from '@/lib/api/types';

export const REGISTERED_API_ROUTES: ApiExplorerRoute[] = [
  // Health & Public
  {
    id: 'health-live',
    name: 'Backend Keepalive Health',
    path: '/health',
    method: 'GET',
    category: 'System',
    description: 'Public backend health probe and uptime keepalive check.',
  },
  {
    id: 'auth-csrf',
    name: 'CSRF Token Generation',
    path: '/auth/csrf-token',
    method: 'GET',
    category: 'Authentication',
    description: 'Retrieves active CSRF token for mutating administrative calls.',
  },
  // User & Profile
  {
    id: 'users-me',
    name: 'Current Session User Profile',
    path: '/users/me',
    method: 'GET',
    category: 'Authentication',
    description: 'Returns profile, role, and permissions of authenticated session.',
  },
  // Dashboard & Metrics
  {
    id: 'dashboard-overview',
    name: 'Dashboard Overview Metrics',
    path: '/admin/dashboard/overview',
    method: 'GET',
    category: 'Analytics',
    description: 'Aggregated real-time metrics for users, orders, and revenue.',
  },
  {
    id: 'dashboard-sales',
    name: 'Sales Trends Telemetry',
    path: '/admin/dashboard/sales',
    method: 'GET',
    category: 'Analytics',
    description: 'Historical revenue and order volume trends.',
    defaultParams: { interval: 'daily' },
  },
  // System Diagnostics
  {
    id: 'system-health',
    name: 'Admin System Health Diagnostics',
    path: '/admin/system-health',
    method: 'GET',
    category: 'Diagnostics',
    description: 'Deep backend health telemetry: database connectivity, redis cache, uptime, and latency.',
  },
  {
    id: 'security-overview',
    name: 'Security Controls Overview',
    path: '/admin/security',
    method: 'GET',
    category: 'Security',
    description: 'Administrative security metrics, active sessions, and intrusion statistics.',
  },
  {
    id: 'audit-logs',
    name: 'System Audit Logs',
    path: '/admin/audit-logs',
    method: 'GET',
    category: 'Audit',
    description: 'Chronological audit trail of administrative actions, mutations, and authentication events.',
    defaultParams: { page: '1', limit: '20' },
  },
  // Commerce & Products
  {
    id: 'products-list',
    name: 'Product Catalog List',
    path: '/products',
    method: 'GET',
    category: 'Catalog',
    description: 'List master product catalog with pagination, filters, and search.',
    defaultParams: { page: '1', limit: '10' },
  },
  {
    id: 'categories-list',
    name: 'Category Hierarchy',
    path: '/categories',
    method: 'GET',
    category: 'Catalog',
    description: 'List categories, taxonomy trees, and specifications.',
  },
  {
    id: 'brands-list',
    name: 'Brand Registry',
    path: '/brands',
    method: 'GET',
    category: 'Catalog',
    description: 'List authorized brand partners and manufacturer profiles.',
  },
  // Inventory
  {
    id: 'inventory-overview',
    name: 'Inventory Stock Overview',
    path: '/admin/inventory/overview',
    method: 'GET',
    category: 'Inventory',
    description: 'SKU stock levels, reorder alerts, and low stock items.',
  },
  {
    id: 'inventory-reservations',
    name: 'Inventory Checkout Reservations',
    path: '/admin/inventory/reservations',
    method: 'GET',
    category: 'Inventory',
    description: 'Active cart checkout stock reservations with TTL.',
  },
  // Orders
  {
    id: 'orders-list',
    name: 'Orders Management List',
    path: '/orders',
    method: 'GET',
    category: 'Orders',
    description: 'Query commercial customer orders with status filter.',
    defaultParams: { page: '1', limit: '10' },
  },
  // Customers
  {
    id: 'customers-list',
    name: 'Customer Directory',
    path: '/admin/customers',
    method: 'GET',
    category: 'Customers',
    description: 'Customer profiles, order histories, and verification status.',
    defaultParams: { page: '1', limit: '10' },
  },
  // Finance
  {
    id: 'finance-summary',
    name: 'Financial Ledger Summary',
    path: '/admin/finance/summary',
    method: 'GET',
    category: 'Finance',
    description: 'Gross merchandise value, net receipts, and pending disbursements.',
  },
  {
    id: 'finance-transactions',
    name: 'Financial Transactions List',
    path: '/admin/finance/transactions',
    method: 'GET',
    category: 'Finance',
    description: 'Ledger transactions, payment gateway fees, and settled orders.',
  },
  // Coupons & Marketing
  {
    id: 'coupons-list',
    name: 'Promotional Coupons List',
    path: '/coupons',
    method: 'GET',
    category: 'Marketing',
    description: 'Active discount codes, usage limits, and redemption statistics.',
  },
  // Support & Reviews
  {
    id: 'support-tickets',
    name: 'Customer Support Tickets',
    path: '/admin/support',
    method: 'GET',
    category: 'Support',
    description: 'Helpdesk tickets, escalations, and customer inquiries.',
  },
  {
    id: 'reviews-list',
    name: 'Product Reviews List',
    path: '/reviews',
    method: 'GET',
    category: 'Feedback',
    description: 'Customer product reviews, star ratings, and moderation flags.',
  },
  // Settings & Governance
  {
    id: 'settings-get',
    name: 'Business Settings',
    path: '/admin/settings',
    method: 'GET',
    category: 'Configuration',
    description: 'Global business parameters, tax profiles, and store configuration.',
  },
  {
    id: 'admin-users-list',
    name: 'Admin Users Roster',
    path: '/admin/users',
    method: 'GET',
    category: 'Governance',
    description: 'List admin users, active roles, and granular permission sets.',
  },
  {
    id: 'roles-list',
    name: 'Role Permissions Matrix',
    path: '/admin/roles',
    method: 'GET',
    category: 'Governance',
    description: 'Defined RBAC role definitions and privilege mappings.',
  },
  {
    id: 'notifications-list',
    name: 'Admin System Notifications',
    path: '/admin/notifications',
    method: 'GET',
    category: 'Notifications',
    description: 'Broadcast notifications and operational system alerts.',
  },
];

export interface DevToolItem {
  id: string;
  label: string;
  category: 'core' | 'health' | 'diagnostics' | 'telemetry' | 'system';
  icon: string;
  description: string;
  backendSupported: boolean;
  endpointHint?: string;
}

export const DEV_TOOLS_ITEMS: DevToolItem[] = [
  {
    id: 'overview',
    label: 'Developer Overview',
    category: 'core',
    icon: 'Terminal',
    description: 'Developer control center with aggregate status, versions, and system telemetry.',
    backendSupported: true,
  },
  {
    id: 'explorer',
    label: 'API Explorer',
    category: 'core',
    icon: 'Compass',
    description: 'Interactive API debugging interface for registered backend endpoints.',
    backendSupported: true,
  },
  {
    id: 'api-health',
    label: 'API Health',
    category: 'health',
    icon: 'Activity',
    description: 'Real-time endpoint reachability, HTTP status codes, and latency benchmarking.',
    backendSupported: true,
    endpointHint: '/health, /admin/system-health',
  },
  {
    id: 'system-health',
    label: 'System Health',
    category: 'health',
    icon: 'Server',
    description: 'Backend system telemetry, Node.js runtime, and operational memory state.',
    backendSupported: true,
    endpointHint: '/admin/system-health',
  },
  {
    id: 'database',
    label: 'Database Health',
    category: 'health',
    icon: 'Database',
    description: 'MongoDB operational connectivity, latency, and catalog query telemetry.',
    backendSupported: true,
    endpointHint: '/admin/system-health',
  },
  {
    id: 'redis',
    label: 'Redis Health',
    category: 'health',
    icon: 'Cpu',
    description: 'Redis in-memory caching layer connectivity, latency, and status.',
    backendSupported: true,
    endpointHint: '/admin/system-health',
  },
  {
    id: 'queues',
    label: 'Queue Health',
    category: 'health',
    icon: 'Layers',
    description: 'BullMQ and background queue worker telemetry and metrics.',
    backendSupported: false,
    endpointHint: '/admin/queues (Not implemented in backend)',
  },
  {
    id: 'jobs',
    label: 'Background Jobs',
    category: 'telemetry',
    icon: 'Clock',
    description: 'Background worker execution telemetry and scheduled outbox tasks.',
    backendSupported: false,
    endpointHint: '/admin/jobs (Not implemented in backend)',
  },
  {
    id: 'webhooks',
    label: 'Webhooks',
    category: 'telemetry',
    icon: 'Webhook',
    description: 'Webhook integration monitors for Razorpay and notification providers.',
    backendSupported: false,
    endpointHint: '/admin/webhooks (Not implemented in backend)',
  },
  {
    id: 'events',
    label: 'Event Logs',
    category: 'telemetry',
    icon: 'ListFilter',
    description: 'Server-side administrative and entity event logs with filters.',
    backendSupported: true,
    endpointHint: '/admin/audit-logs',
  },
  {
    id: 'errors',
    label: 'Error Logs',
    category: 'telemetry',
    icon: 'AlertTriangle',
    description: 'Sanitized error reports, warning events, and failure telemetry.',
    backendSupported: true,
    endpointHint: '/admin/audit-logs (FAILED status)',
  },
  {
    id: 'requests',
    label: 'Request Logs',
    category: 'telemetry',
    icon: 'FileCode2',
    description: 'HTTP request diagnostics, proxy session telemetry, and response times.',
    backendSupported: true,
    endpointHint: 'DevTools In-Session Proxy Telemetry',
  },
  {
    id: 'trace',
    label: 'Request Trace',
    category: 'diagnostics',
    icon: 'GitBranch',
    description: 'Trace specific Request IDs across controllers, database queries, and audit logs.',
    backendSupported: true,
    endpointHint: '/admin/audit-logs, Request ID Header',
  },
  {
    id: 'audit',
    label: 'Audit Debugger',
    category: 'diagnostics',
    icon: 'History',
    description: 'Deep administrative audit debugger tracing admin actions to mutations.',
    backendSupported: true,
    endpointHint: '/admin/audit-logs',
  },
  {
    id: 'cache',
    label: 'Cache',
    category: 'diagnostics',
    icon: 'Zap',
    description: 'Cache layer status, TTL policies, and safe invalidation diagnostics.',
    backendSupported: false,
    endpointHint: '/admin/cache (Not implemented in backend)',
  },
  {
    id: 'flags',
    label: 'Feature Flags',
    category: 'system',
    icon: 'Flag',
    description: 'Backend dynamic feature toggle configuration and environment flags.',
    backendSupported: false,
    endpointHint: '/admin/feature-flags (Not implemented in backend)',
  },
  {
    id: 'env',
    label: 'Environment',
    category: 'system',
    icon: 'Shield',
    description: 'Safe environment configuration diagnostics (0 secrets exposed).',
    backendSupported: true,
    endpointHint: 'Server Environment Descriptor',
  },
  {
    id: 'integrations',
    label: 'Integration Status',
    category: 'system',
    icon: 'Link2',
    description: 'Connection diagnostics for MongoDB, Redis, API Gateway, and Logistics.',
    backendSupported: true,
    endpointHint: 'Multi-service Probe Verification',
  },
  {
    id: 'release',
    label: 'Release / Version',
    category: 'system',
    icon: 'Tag',
    description: 'Application release metadata, backend version, and runtime environment.',
    backendSupported: true,
    endpointHint: '/health, /admin/system-health, package.json',
  },
  {
    id: 'security',
    label: 'Security Diagnostics',
    category: 'system',
    icon: 'Lock',
    description: 'Read-only security controls audit: CSRF, CORS, RBAC, and HTTP headers.',
    backendSupported: true,
    endpointHint: '/admin/security, /auth/csrf-token, Security Headers',
  },
];
